import { useMemo, useRef, useState } from "react";
import { Check, ChevronRight, FileText, ImagePlus, MapPin, Menu, Paperclip, Phone, ShieldCheck, Sparkles, UploadCloud, Video, X } from "lucide-react";
import { INDIA_LOCATIONS } from "../data/indiaLocations";
import "./SubmitProblem.css";

const categories = ["Education", "Agriculture", "Healthcare", "Water Resources", "Environment", "Energy", "Urban Development", "Rural Development", "Accessibility", "Public Administration", "Transportation", "Waste Management", "Digital Infrastructure", "Employment & Livelihood", "Disaster Management", "Public Safety", "Housing", "Sanitation", "Tourism", "Other"];
const affectedGroups = ["Farmers", "Students", "Children", "Women", "Elderly people", "Persons with disabilities", "Local residents", "Workers", "Businesses", "Healthcare workers", "Government employees", "Other"];
const stages = ["Submitted", "AI Analysis", "Authority Review", "Institution Matching", "Solution Development", "Field Testing", "Deployment", "Impact Measurement"];
const initialForm = { title: "", description: "", country: "India", state: "", district: "", city: "", locality: "", pin: "", people: "", affected: [], urgency: "Medium", impact: "Local", duration: "", current: "", solution: "", name: "", phone: "", email: "", contact: "Either", anonymous: false, accurate: false, consent: false };

function Field({ label, required, hint, children }) {
  return <label className="js-field"><span className="js-label">{label} {required && <b>*</b>}</span>{children}{hint && <small>{hint}</small>}</label>;
}
function Section({ number, eyebrow, title, children }) {
  return <section className="js-section"><div className="js-section-heading"><span className="js-step-number">{number}</span><div><span className="js-eyebrow">{eyebrow}</span><h2>{title}</h2></div></div>{children}</section>;
}
function TextInput(props) { return <input className="js-input" {...props} />; }
function SelectInput({ children, ...props }) { return <select className="js-input" {...props}>{children}</select>; }
function Dropzone({ label, icon: Icon, accept, multiple, files, onFiles, onRemove, note }) {
  const inputRef = useRef(null);
  const process = (list) => onFiles(Array.from(list).filter((file) => file.size <= 10 * 1024 * 1024));
  return <div className="js-upload"><button type="button" className="js-dropzone" onClick={() => inputRef.current?.click()} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); process(event.dataTransfer.files); }}><Icon size={22} /><strong>{label}</strong><span>Drag and drop or <em>browse files</em></span><small>{note}</small></button><input ref={inputRef} type="file" accept={accept} multiple={multiple} hidden onChange={(event) => process(event.target.files)} />{files.length > 0 && <div className="js-file-list">{files.map((file, index) => <div className="js-file" key={`${file.name}-${index}`}>{file.type.startsWith("image/") ? <img src={URL.createObjectURL(file)} alt="" /> : <FileText size={18} />}<span>{file.name}</span><button type="button" aria-label={`Remove ${file.name}`} onClick={() => onRemove(index)}><X size={15} /></button></div>)}</div>}</div>;
}

export default function SubmitProblem() {
  const [form, setForm] = useState(initialForm);
  const [photos, setPhotos] = useState([]);
  const [video, setVideo] = useState([]);
  const [documents, setDocuments] = useState([]);
  const [location, setLocation] = useState(null);
  const [locationStatus, setLocationStatus] = useState("");
  const [errors, setErrors] = useState({});
  const [submitted, setSubmitted] = useState(false);

  const selectedState = useMemo(() => INDIA_LOCATIONS.find((item) => item.name === form.state), [form.state]);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const toggleAffected = (item) => update("affected", form.affected.includes(item) ? form.affected.filter((value) => value !== item) : [...form.affected, item]);
  const useLocation = () => {
    if (!navigator.geolocation) { setLocationStatus("Location is not supported by this browser."); return; }
    setLocationStatus("Requesting your location...");
    navigator.geolocation.getCurrentPosition((position) => { setLocation({ lat: position.coords.latitude.toFixed(6), lng: position.coords.longitude.toFixed(6) }); setLocationStatus("Location captured securely"); }, () => setLocationStatus("We could not access your location. You can continue without GPS."));
  };
  const validate = () => {
    const next = {};
    ["title", "description", "state", "district", "people", "duration", "name", "phone"].forEach((key) => { if (!String(form[key]).trim()) next[key] = "This field is required"; });
    if (form.phone && !/^[6-9]\d{9}$/.test(form.phone.replace(/\s/g, ""))) next.phone = "Enter a valid 10-digit Indian mobile number";
    if (form.pin && !/^\d{6}$/.test(form.pin)) next.pin = "PIN code must contain 6 digits";
    if (!form.accurate) next.accurate = "Please confirm the accuracy of this information";
    if (!form.consent) next.consent = "Please confirm the review consent";
    setErrors(next); return Object.keys(next).length === 0;
  };
  const submit = (event) => { event.preventDefault(); if (!validate()) { window.scrollTo({ top: 0, behavior: "smooth" }); return; } setSubmitted(true); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const reset = () => { setForm(initialForm); setPhotos([]); setVideo([]); setDocuments([]); setLocation(null); setErrors({}); setSubmitted(false); };

  if (submitted) return <div className="js-page"><Header /><main className="js-success"><div className="js-success-icon"><Check size={34} /></div><span className="js-eyebrow">Submission received</span><h1>Problem Submitted<br /><i>Successfully!</i></h1><p>Your problem has been successfully submitted and is awaiting verification.</p><div className="js-confirmation"><div><span>Problem ID</span><strong>IND-2026-000001</strong></div><div><span>Submission Date</span><strong>{new Date().toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</strong></div><div><span>Current Status</span><strong className="js-status">Submitted</strong></div></div><div className="js-tracker">{stages.map((stage, index) => <div className={`js-track-item ${index === 0 ? "active" : ""}`} key={stage}><span>{index === 0 ? <Check size={14} /> : index + 1}</span><label>{stage}</label>{index < stages.length - 1 && <div className="js-track-line" />}</div>)}</div><div className="js-success-actions"><button type="button" className="js-primary" onClick={() => alert("Tracking will be available once verification begins.")}>Track My Problem <ChevronRight size={18} /></button><button type="button" className="js-secondary" onClick={reset}>Submit Another Problem</button></div></main></div>;

  return <div className="js-page"><Header /><main><section className="js-hero"><div><span className="js-kicker"><span /> PAN-INDIA CIVIC INNOVATION NETWORK</span><h1>Turn a local problem<br /><i>into a national solution.</i></h1><p>Report real-world challenges and connect them with institutions, innovators and organizations that can create meaningful solutions.</p></div><div className="js-hero-stamp"><Sparkles size={18} /><span>AI-assisted<br /><b>problem routing</b></span></div></section><div className="js-progress" id="journey"><span className="active"><b>01</b> Problem report</span><span><b>02</b> Verification</span><span><b>03</b> Solution journey</span></div><form id="form" onSubmit={submit} noValidate>{Object.keys(errors).length > 0 && <div className="js-error-summary" role="alert"><strong>Please review your submission</strong><span>{Object.keys(errors).length} item{Object.keys(errors).length === 1 ? "" : "s"} need your attention before you can submit.</span></div>}
    <Section number="01" eyebrow="Start with the story" title="Problem details"><div className="js-grid two"><Field label="Problem title" required><TextInput value={form.title} onChange={(e) => update("title", e.target.value)} placeholder="e.g. Lack of clean drinking water in our locality" /></Field><div className="js-ai-note"><Sparkles size={20} /><div><strong>AI will classify this problem</strong><span>One problem can belong to multiple domains. Our system will identify the right categories automatically.</span><div className="js-tags">{categories.slice(0, 8).map((category) => <span key={category}>{category}</span>)}<span>+ more</span></div></div></div></div><Field label="Problem description" required><textarea className="js-textarea" rows="5" value={form.description} onChange={(e) => update("description", e.target.value)} placeholder="Describe the problem in detail, who is affected, how long it has existed, its causes, and any other useful information." /></Field></Section>
    <Section number="02" eyebrow="Pinpoint the place" title="Location"><div className="js-grid three"><Field label="Country" required><TextInput value={form.country} readOnly /></Field><Field label="State / Union Territory" required><SelectInput value={form.state} onChange={(e) => { update("state", e.target.value); update("district", ""); }}><option value="">Select state or UT</option>{INDIA_LOCATIONS.map((item) => <option key={item.name}>{item.name}</option>)}</SelectInput></Field><Field label="District" required><SelectInput value={form.district} onChange={(e) => update("district", e.target.value)} disabled={!selectedState}><option value="">{selectedState ? "Select district" : "Select a state first"}</option>{selectedState?.districts.map((district) => <option key={district}>{district}</option>)}</SelectInput></Field><Field label="City / Block"><TextInput value={form.city} onChange={(e) => update("city", e.target.value)} placeholder="Enter city or block" /></Field><Field label="Village / Locality"><TextInput value={form.locality} onChange={(e) => update("locality", e.target.value)} placeholder="Enter locality" /></Field><Field label="PIN code"><TextInput inputMode="numeric" value={form.pin} onChange={(e) => update("pin", e.target.value)} placeholder="6-digit PIN" /></Field></div><div className="js-location-row"><div><h3><MapPin size={18} /> GPS location</h3><p>{location ? `Latitude ${location.lat}  ·  Longitude ${location.lng}` : "Adding a GPS pin helps responders understand the exact context."}</p>{locationStatus && <small>{locationStatus}</small>}</div><button type="button" className="js-location-button" onClick={useLocation}><MapPin size={17} /> Use my current location</button></div><div className="js-map-placeholder"><MapPin size={28} /><div><strong>Map view</strong><span>Leaflet + OpenStreetMap location preview will appear here</span></div><span className="js-map-badge">MAP READY</span></div></Section>
    <Section number="03" eyebrow="Show the scale" title="Problem impact"><div className="js-grid three"><Field label="People affected" required><TextInput type="number" min="1" value={form.people} onChange={(e) => update("people", e.target.value)} placeholder="Approximate number" /></Field><Field label="Problem urgency"><SelectInput value={form.urgency} onChange={(e) => update("urgency", e.target.value)}>{["Low", "Medium", "High", "Critical"].map((item) => <option key={item}>{item}</option>)}</SelectInput></Field><Field label="Expected impact"><SelectInput value={form.impact} onChange={(e) => update("impact", e.target.value)}>{["Local", "District", "State", "National"].map((item) => <option key={item}>{item}</option>)}</SelectInput></Field><Field label="How long has this existed?" required><SelectInput value={form.duration} onChange={(e) => update("duration", e.target.value)}><option value="">Select duration</option>{["Less than 1 month", "1–6 months", "6 months–1 year", "1–5 years", "More than 5 years"].map((item) => <option key={item}>{item}</option>)}</SelectInput></Field></div><div className="js-check-group"><span className="js-label">Who is affected?</span><div className="js-check-grid">{affectedGroups.map((item) => <label className={`js-check ${form.affected.includes(item) ? "selected" : ""}`} key={item}><input type="checkbox" checked={form.affected.includes(item)} onChange={() => toggleAffected(item)} /><span>{item}</span></label>)}</div></div></Section>
    <Section number="04" eyebrow="Build the evidence" title="Photos, video & documents"><div className="js-upload-grid"><Dropzone label="Add photos" icon={ImagePlus} accept="image/jpeg,image/png" multiple files={photos} onFiles={setPhotos} onRemove={(index) => setPhotos(photos.filter((_, i) => i !== index))} note="JPG, JPEG, PNG · max 10 MB each" /><Dropzone label="Add a video" icon={Video} accept="video/mp4,video/quicktime" files={video} onFiles={(files) => setVideo(files.slice(0, 1))} onRemove={() => setVideo([])} note="MP4, MOV · max 10 MB" /><Dropzone label="Supporting documents" icon={Paperclip} accept=".pdf,.doc,.docx" multiple files={documents} onFiles={setDocuments} onRemove={(index) => setDocuments(documents.filter((_, i) => i !== index))} note="PDF, DOC, DOCX · max 10 MB each" /></div></Section>
    <Section number="05" eyebrow="Imagine better" title="Current situation & expected solution"><Field label="What is currently being done to solve this problem?"><textarea className="js-textarea" rows="4" value={form.current} onChange={(e) => update("current", e.target.value)} placeholder="Tell us about any existing efforts, workarounds or support." /></Field><Field label="What kind of solution do you expect?"><textarea className="js-textarea" rows="4" value={form.solution} onChange={(e) => update("solution", e.target.value)} placeholder="Describe the improvement you would like to see." /><small>You do not need to know the technical solution. Simply describe what improvement you would like to see.</small></Field></Section>
    <Section number="06" eyebrow="Stay connected" title="Contact information"><div className="js-grid two"><Field label="Your name" required><TextInput value={form.name} onChange={(e) => update("name", e.target.value)} placeholder="Enter your full name" /></Field><Field label="Phone number" required><TextInput inputMode="tel" value={form.phone} onChange={(e) => update("phone", e.target.value)} placeholder="10-digit mobile number" /></Field><Field label="Email address"><TextInput type="email" value={form.email} onChange={(e) => update("email", e.target.value)} placeholder="you@example.com" /></Field><Field label="Preferred contact method"><div className="js-radio-row">{["Phone", "Email", "Either"].map((item) => <label key={item}><input type="radio" name="contact" checked={form.contact === item} onChange={() => update("contact", item)} /> {item}</label>)}</div></Field></div><label className="js-anonymous"><input type="checkbox" checked={form.anonymous} onChange={(e) => update("anonymous", e.target.checked)} /><span><ShieldCheck size={18} /><b>Submit anonymously</b><small>Your name will not be publicly displayed, while secure contact details can still be used for verification.</small></span></label></Section>
    <Section number="07" eyebrow="One final check" title="Declaration"><label className={`js-declaration ${errors.accurate ? "has-error" : ""}`}><input type="checkbox" checked={form.accurate} onChange={(e) => update("accurate", e.target.checked)} /><span>I confirm that the information provided is accurate to the best of my knowledge.</span></label><label className={`js-declaration ${errors.consent ? "has-error" : ""}`}><input type="checkbox" checked={form.consent} onChange={(e) => update("consent", e.target.checked)} /><span>I agree that authorized government officials, universities, research institutions and approved innovation partners may review this problem for the purpose of developing a solution.</span></label></Section><div className="js-submit-row"><div><ShieldCheck size={19} /><span>Your submission is encrypted and routed to the appropriate authority.</span></div><button type="submit" className="js-primary js-submit">Submit problem <ChevronRight size={20} /></button></div></form></main><footer><strong>JANSETU</strong><span>From community problems to innovative solutions.</span><span>Built for every state and union territory of India.</span></footer></div>;
}

function Header() { return <header className="js-header"><a href="/" className="js-brand"><span>जन</span>SETU</a><span className="js-brand-sub">CIVIC INNOVATION PLATFORM</span><nav><a href="#form">Report a problem</a><a href="#journey">How it works</a><button type="button" aria-label="Open menu"><Menu size={20} /></button></nav></header>; }
